import type { Resource } from '../lib/resource';

export const resources: Resource[] = [
  {
    id: '0',
    title: 'Planteamiento del problema de investigación: desde la óptica cuantitativa y cualitativa',
    description: 'TBD',
    type: 'Llibre',
    dimension: 'Planificació de la recerca',
    subdimension: 'Elecció del tema i pregunta de recerca',
    level: 2,
    language: 'Español',
    url: 'https://www.uca.ac.cr/wp-content/uploads/2017/10/Investigacion.pdf',
  },
  {
    id: '1',
    title: '¿Cómo escoger un tema de investigación y construir una pregunta de investigación?',
    description: 'TBD',
    type: 'Article',
    dimension: 'Planificació de la recerca',
    subdimension: 'Elecció del tema i pregunta de recerca',
    level: 1,
    language: 'Español',
    url: 'https://www.redalyc.org/pdf/1794/179421472004.pdf',
  },
  {
    id: '2',
    title: 'La formulació dels objectius de recerca',
    description: 'TBD',
    type: 'Recurs web',
    dimension: 'Planificació de la recerca',
    subdimension: "Formulació d'objectius i hipòtesis",
    level: 1,
    language: 'Català',
    url: 'https://www.eltefege.eu/index.php/2018/03/15/apunt-4-la-formulacio-dels-objectius-de-recerca/',
  },
  {
    id: '3',
    title: 'Transcripció de Dades Plurilingües/Multimodals',
    description: 'TBD',
    type: 'Recurs web',
    dimension: 'Fonamentació teòrica',
    subdimension: "Cerca d'informació",
    level: 2,
    language: 'Català',
    url: 'https://tutorialfortrans.blogspot.com/',
  },
  {
    id: '4',
    title: 'Good Literature Searching',
    description: 'TBD',
    type: 'Article',
    dimension: 'Fonamentació teòrica',
    subdimension: "Cerca d'informació",
    level: 1,
    language: 'English',
    url: 'https://www.review.mai.ac.nz/mrindex/TK/article/view/53/53.html',
  },
  {
    id: '5',
    title: 'Art of reading a journal article: Methodically and effectively',
    description: 'TBD',
    type: 'Article',
    dimension: 'Fonamentació teòrica',
    subdimension: "Cerca d'informació",
    level: 1,
    language: 'English',
    url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3687192/',
  },
  {
    id: '6',
    title: 'Eines i recursos documentals per al treball de recerca en Educació',
    description: 'TBD',
    type: 'Presentació',
    dimension: 'Fonamentació teòrica',
    subdimension: 'Eines per cercar informació',
    level: 2,
    language: 'Català',
    url: 'https://ddd.uab.cat/record/142532',
  },
  {
    id: '7',
    title: 'Cerca i gestió de la informació: les principals fonts d\'informació en Educació, Psicologia i Logopèdia',
    description: 'TBD',
    type: 'Presentació',
    dimension: 'Fonamentació teòrica',
    subdimension: 'Eines per cercar informació',
    level: 1,
    language: 'Català',
    url: 'https://ddd.uab.cat/record/174633',
  },
  {
    id: '8',
    title: 'Approaching literature review for academic purposes',
    description: 'TBD',
    type: 'Article',
    dimension: 'Fonamentació teòrica',
    subdimension: "Estratègies d'elaboració del text",
    level: 1,
    language: 'English',
    url: 'https://www.scielo.br/scielo.php?pid=S1807-59322019000100318&script=sci_arttext',
  },
  {
    id: '9',
    title: 'Best-Practice Recommendations of Methodological Literature Reviews',
    description: 'TBD',
    type: 'Article',
    dimension: 'Fonamentació teòrica',
    subdimension: "Estratègies d'elaboració del text",
    level: 2,
    language: 'English',
    url: 'https://journals.sagepub.com/doi/full/10.1177/1094428120943281',
  },
  {
    id: '10',
    title: 'Recerca qualitativa sobre educació plurilingüe',
    description: 'TBD',
    type: 'Llibre',
    dimension: 'Disseny i aplicació',
    subdimension: 'Dissenys metodològics',
    level: 2,
    language: 'Català',
    url: 'https://research-publishing.net/publication/978-1-908416-47-6.pdf',
  },
  {
    id: '11',
    title: 'Studying the Use of Research Evidence: A Review of Methods',
    description: 'TBD',
    type: 'Llibre',
    dimension: 'Disseny i aplicació',
    subdimension: 'Dissenys metodològics',
    level: 2,
    language: 'English',
    url: 'https://wtgrantfoundation.org/library/uploads/2019/02/A-Review-of-Methods-FINAL003.pdf',
  },
  {
    id: '12',
    title: 'Historias de vida',
    description: 'TBD',
    type: 'Article',
    dimension: 'Disseny i aplicació',
    subdimension: 'Dissenys metodològics',
    level: 1,
    language: 'Español',
    url: 'https://revistas.upr.edu/index.php/griot/article/download/1775/1568',
  },
  {
    id: '13',
    title: 'Quantitatiu o Qualitatiu? Escull!',
    description: 'TBD',
    type: 'Quiz',
    dimension: 'Disseny i aplicació',
    subdimension: 'Dissenys metodològics',
    level: 1,
    language: 'Català',
    url: 'https://goo.gl/ZMy8E6',
  },
  {
    id: '14',
    title: 'A guide for naming research studies',
    description: 'TBD',
    type: 'Article',
    dimension: 'Disseny i aplicació',
    subdimension: 'Dissenys metodològics',
    level: 1,
    language: 'English',
    url: 'https://www.redalyc.org/pdf/337/33770318.pdf',
  },
  {
    id: '15',
    title: 'Discussió vs conclusions: principis i directrius',
    description: 'TBD',
    type: 'Vídeo',
    dimension: 'Discussió i conclusions',
    subdimension: '',
    level: 1,
    language: 'Català',
    url: 'https://www.youtube.com/watch?v=_0MwkPVxLYo',
  },
  {
    id: '16',
    title: "What's new in APA Style 7th Edition",
    description: 'TBD',
    type: 'Vídeo',
    dimension: 'Bibliografia',
    subdimension: '',
    level: 1,
    language: 'English',
    url: 'https://www.youtube.com/watch?v=jOVZp8m0PCM',
  },
  {
    id: '17',
    title: 'Com citar i referenciar en els textos acadèmics',
    description: 'TBD',
    type: 'Llibre',
    dimension: 'Bibliografia',
    subdimension: '',
    level: 1,
    language: 'Català',
    url: 'https://ddd.uab.cat/record/145881',
  },
  {
    id: '18',
    title: 'Com elaborar el Treball Final de Grau',
    description: 'TBD',
    type: 'Vídeo',
    dimension: 'Comunicació i TIC',
    subdimension: 'Comunicació escrita i oral de la recerca',
    level: 1,
    language: 'Català',
    url: 'https://www.youtube.com/watch?v=8NtqeUeGJTM',
  },
];